#MQTT_SERVER
MQTT_SERVER_IP = "localhost"
MQTT_SERVER_PORT = 1883
MQTT_USERNAME = "server"
MQTT_PASSWORD = "server123"

#INFLUXDB
INFLUXDB_IP = "http://localhost"
INFLUXDB_PORT = 8086
INFLUXDB_TOKEN = "g0f6rFPPiAPqxPyuCmbR57WFCoeIV0-RlexjybpipavSP-vWGS7ZeSsXm_jXx8ppX-34xyyJa2sh-6MQoko_hg=="
INFLUXDB_ORG = "wilamare"
INFLUXDB_DEFAULT_BUCKET = "homesolar"

#PYTHON_DEBUG
DEBUG = False